 platform :ios, '9.0'

target 'RxSwiftExample' do
  
  use_frameworks!
    pod 'SnapKit', '4.2.0'
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0' 
    pod 'IQKeyboardManagerSwift', '6.5.5'

end
