 platform :ios, '9.0'

target 'RxSwiftExample' do
  
  use_frameworks!

  pod 'SnapKit', '4.2.0'
  pod 'Localize-Swift', '2.0.0'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Moya/RxSwift', '~> 13.0'
  pod 'SwiftyJSON', '4.2.0'
  pod 'SwiftLint', '0.29.1'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyGif'
  pod 'Kingfisher'
  pod 'iCarousel'
  pod 'Shimmer', '~> 1.0.2'
  
end
