 platform :ios, '9.0'

target 'RxSwiftExample' do
  
  use_frameworks!
    pod 'SnapKit', '4.2.0'
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0' 
    pod 'IQKeyboardManagerSwift', '6.5.5'
    pod 'Alamofire', '~> 4.2'
    pod 'SwiftyJSON', '~> 4.0'
    
    pod 'Firebase'
    pod 'Firebase/Analytics'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Messaging'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/Performance'
    pod 'Firebase/Crashlytics'
    
end
